### ISSUE TITLE
py.test support

### ISSUE THREAD

**Issue by jayvdb** [venmo/nose-detecthttp#5]
I cant find any py.test plugin that provides similar functionality, so I was wondering if it would be reasonable to add py.test support to this plugin, despite the name.  I see many good addons which support both nose and py.test in the same plugin, so I guess there is some benefits in doing that, if only that a unified addon has a larger userbase to help with maintenance.
If you're not completely opposed to the idea, I'll give it a go and you can reconsider after I've got it working.

**Comment by simon-weber** [comment]
Sure; sounds good to me!

In case you're interested in examples, I know https://github.com/wolever/nose-parameterized did the nose -> nose/pytest switch at some point.

**Comment by jayvdb** [comment]
flaky is another which supports both.

Also I found https://github.com/andymckay/nose-blockage and https://github.com/rob-b/pytest-blockage , but they only target `httplib.HTTPConnection.__init__` and `smtplib.SMTP.__init__`, and have no tests.

**Comment by simon-weber** [comment]
Ah, good to know about those alternatives; I don't remember seeing them before.

**Comment by jayvdb** [comment]
Thanks so much for this.
Now it just needs a new name .. ;-)
